Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.7"
  config.hostsupdater.aliases = ["developer.local"]
  config.vm.synced_folder "app", "/home/vagrant/app"
  config.vm.provision "shell", path: "environment/provision.sh"
end
