
Vagrant.configure("2") do |config|
  config.vagrant.plugins = ("vagrant-hostsupdater")
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.50.7"
  config.hostsupdater.aliases = ["developer.local"]
  config.vm.provision "shell", path: "provision.sh"
end
